# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender_profile', '0002_auto_20171120_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
